---

- hosts: all
  become: true
  tasks:

  - name: install apache & php packages
    apt:
      name:
       - "{{ apache_package  }}"
       - "{{ php_packege }}"
      state: latest
      update_cache: yes

