---

- hosts: all
  become: true
  tasks:

  - name: update indexes
    apt:
      update_cache: yes

  - name: install apache2 package
    apt:
      name: apache2
      state: absent

  - name: update apache libs
    apt:
      name: libapache2-mod-php
      state: absent
