---

- hosts: all
  become: true
  tasks:

  - name: update Linux
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Debian"

  - name: install apache & php packages
    apt:
      name:
       - "{{ apache_package  }}"
       - "{{ php_package }}"
      state: latest
      update_cache: yes

  - name: change email address by regexp
    lineinfile:
      path: /etc/apache2/apache2.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin iurii@iurii.con
    register: testvariable

- hosts: justhost
  become: true
  tasks:

  - name: install MariaDB package
    tags: maria,db
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"

- hosts: justhost
  become: true
  tasks:

  - name: install samba
    package:
      name: samba
      state: latest

  - name: copy HTML website
    tags: site
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    tags: terraform
    unarchive:
      src: /home/iurii/Downloads/terraform_1.9.6_linux_arm64.zip
      dest: /usr/local/bin
      #remote_src: yes
      owner: root
      group: root
      mode: 0755

  - name: create testuser
    tags: adduser
    user:
      name: testuser
      groups: iurii

  - name: add key for testuser
    authorized_key:
      user: testuser
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMSwQvlhSIsZEtlpwNnXaURP6j5XIXQn2mSWVUwCU0w2 ansible"

  - name: add testuser to sudoers
    tags: sudoers
    copy:
      src: sudoers_testuser
      dest: /etc/sudoers.d/testuser
      owner: testuser
      group: iurii
      mode: 0440


- hosts: all
  become: true
  roles:
    - allrole

- hosts: justhost
  become: true
  roles:
    - justhostrole
