---

- hosts: all
  become: true
  tasks:

  - name: update Linux
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"

  - name: install apache & php packages
    apt:
      name:
       - "{{ apache_package  }}"
       - "{{ php_package }}"
      state: latest
      update_cache: yes

- hosts: all
  become: true
  tasks:

  - name: install MariaDB package
    tags: maria,db
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"

- hosts: justhost
  become: true
  tasks:

  - name: install samba
    package:
      name: samba
      state: latest
  - name: capy HTML website
    tags: site
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    tags: terraform
    unarchive:
      src: /home/iurii/Downloads/terraform_1.9.6_linux_arm64.zip
      dest: /usr/local/bin
      #remote_src: yes
      owner: root
      group: root
      mode: 0755
