- name: install MariaDB package
    tags: maria,db
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"

- name: install samba
  package:
    name: samba
    state: latest
